// Book data parsed from Reading List.csv

export type ReadingStatus = 'want_to_read' | 'reading' | 'read';

export const READING_STATUS_LABELS: Record<ReadingStatus, string> = {
  want_to_read: 'Want to Read',
  reading: 'Reading',
  read: 'Read',
};

export function getReadingStatusLabel(status?: ReadingStatus): string {
  if (!status) return READING_STATUS_LABELS.want_to_read;
  return READING_STATUS_LABELS[status];
}

export interface Book {
  id: string;
  title: string;
  author?: string;
  genre: string;
  pages?: number;
  notes?: string;
  priority?: string;
}

export interface RatingSource {
  source: 'Google Books' | 'Open Library' | 'Goodreads' | 'Amazon';
  rating?: number;
  ratingsCount?: number;
  url?: string;
}

export interface BookWithDetails extends Book {
  description?: string;
  ratings: RatingSource[];
  coverImage?: string;
  isbn?: string;
  publishedDate?: string;
  publisher?: string;
  subjects?: string[];
  goodreadsUrl?: string;
  amazonUrl?: string;
  deducedGenre?: string; // Genre deduced from API subjects, used to set book.genre if not already set
  needsAuthorClarification?: boolean; // Flag when multiple authors found for a book
  detailsFetchedAt?: string; // ISO date string of when details were last fetched
  read?: boolean; // Whether the user has read this book (deprecated, use readingStatus)
  readingStatus?: ReadingStatus; // Current reading status
}

// Parse title to extract author if embedded (e.g., "Elon Musk by Walter Isaacson")
function parseTitle(rawTitle: string): { title: string; author?: string } {
  // Pattern: "Title by Author" or "Title - Author"
  const byMatch = rawTitle.match(/^(.+?)\s+by\s+(.+)$/i);
  if (byMatch) {
    return { title: byMatch[1].trim(), author: byMatch[2].trim() };
  }

  const dashMatch = rawTitle.match(/^(.+?)\s+-\s+(.+)$/);
  if (dashMatch) {
    // Check if second part looks like an author name (capitalized words)
    const secondPart = dashMatch[2].trim();
    if (/^[A-Z][a-z]+(\s+[A-Z][a-z]+)*$/.test(secondPart)) {
      return { title: dashMatch[1].trim(), author: secondPart };
    }
  }

  return { title: rawTitle.trim() };
}

// Normalize genre names
function normalizeGenre(genre: string): string {
  const genreMap: Record<string, string> = {
    'Psychology/Behaviorial Econ': 'Psychology & Behavioral Economics',
    'Psychology/Behavioral Econ': 'Psychology & Behavioral Economics',
    'Evolution/Biology/Nature': 'Science & Nature',
    'Math/Other Science': 'Science & Mathematics',
    'History/War': 'History & War',
    'History/War/Fiction': 'Historical Fiction',
    'Philosophy/Life Improvement': 'Philosophy & Self-Improvement',
    'Business/Economics': 'Business & Economics',
    'Culture/Society': 'Culture & Society',
    'Travel/Adventure': 'Travel & Adventure',
    'Biography/Memoir': 'Biography & Memoir',
    'Religion/Art': 'Religion & Art',
    'Crime/Drugs': 'Crime & Drugs',
    'Politics': 'Politics',
    'Fiction': 'Fiction',
    'History': 'History',
    'Politics and Bio/Memoir': 'Politics',
  };

  return genreMap[genre] || genre || 'Uncategorized';
}

// Raw book data from CSV (filtered to exclude crossed out books with X priority)
const rawBooks: Array<{ title: string; genre: string; pages?: number; notes?: string; priority?: string }> = [
  { title: "Elon Musk by Walter Isaacson", genre: "", priority: "" },
  { title: "1929", genre: "", priority: "" },
  { title: "The West: History of an Idea", genre: "", priority: "" },
  { title: "Violent Saviors: The West's Conquest of the Rest", genre: "", priority: "" },
  { title: "Careless People", genre: "", priority: "" },
  { title: "Zbig", genre: "", priority: "" },
  { title: "Gods of New York", genre: "", priority: "" },
  { title: "Odyssey Moscow", genre: "", priority: "" },
  { title: "Nothing is True but Everything is Possible", genre: "", priority: "" },
  { title: "Paper of Wreckage", genre: "", priority: "" },
  { title: "Who Knew by Diller", genre: "", priority: "" },
  { title: "Bird School by Adam Nicolson", genre: "", priority: "" },
  { title: "History and Class Consciousness by Lukacs", genre: "", priority: "" },
  { title: "House of War", genre: "", priority: "" },
  { title: "Day in the Life of Ancient Rome by Angela", genre: "", priority: "" },
  { title: "The Peloponnesian War by Donald Kagan", genre: "", priority: "" },
  { title: "How Countries Go Broke by Dalio", genre: "", priority: "" },
  { title: "The Art of Uncertainty by Spiegelhalter", genre: "", priority: "" },
  { title: "The First Man in Rome by Colleen McCullough", genre: "", priority: "" },
  { title: "The Fall of the Roman Empire by Peter Heather", genre: "", priority: "" },
  { title: "The Limits to Capital by David Harvey", genre: "", priority: "" },
  { title: "Four Seasons by Isadore Sharp", genre: "", priority: "" },
  { title: "Unruly by Sean West", genre: "", priority: "" },
  { title: "No Trade is Free by Lighthizer", genre: "", priority: "" },
  { title: "Money: A True Story of a Made Up Thing by Goldstein", genre: "", priority: "" },
  { title: "Prisoners of Geography", genre: "", priority: "" },
  { title: "Currency Wars", genre: "", priority: "" },
  { title: "The Man Who Ran Washington", genre: "", priority: "" },
  { title: "From Dawn to Decadence", genre: "", priority: "" },
  { title: "Are We Smart Enough to Know How Smart Animals Are", genre: "", priority: "" },
  { title: "Geopolitical Alpha: An Investment Framework for Predicting the Future", genre: "", priority: "" },
  { title: "Big Debt Crises by Dalio", genre: "", priority: "" },
  { title: "How Finance Works", genre: "", priority: "" },
  { title: "The Wealth and Poverty of Nations", genre: "", priority: "" },
  { title: "Chain of Fire", genre: "", priority: "" },
  { title: "Blood and Treasure by Weldon", genre: "", priority: "" },
  { title: "The Tragedy of American Diplomacy", genre: "", priority: "" },
  { title: "The Irony of American History", genre: "", priority: "" },
  { title: "A Bend in the River", genre: "", priority: "" },
  { title: "The Rule of Laws by Pirie", genre: "", priority: "" },
  { title: "The Birth of Plenty", genre: "", priority: "" },
  { title: "The Art of Not Being Governed", genre: "", priority: "" },
  { title: "The Grand Strategy of the Roman Empire", genre: "", priority: "" },
  { title: "Dress for Success", genre: "", priority: "" },
  { title: "All the King's Men", genre: "", priority: "" },
  { title: "The Narrow Corridor", genre: "", priority: "" },
  { title: "Where Credit is Due", genre: "", notes: "African debt", priority: "" },
  { title: "King of Kings", genre: "", notes: "Iranian revolution", priority: "" },
  { title: "The Gatekeepers", genre: "", notes: "CoS book", priority: "" },
  { title: "Day of the Jackal", genre: "", priority: "" },
  { title: "The Wayfinder", genre: "", priority: "" },
  { title: "Profiles in Courage", genre: "", priority: "" },
  { title: "The Company by Littell", genre: "", priority: "" },
  { title: "Across the Fence", genre: "", priority: "" },
  { title: "God is an Englishman", genre: "", priority: "" },
  { title: "Age of Uncertainty", genre: "", priority: "" },
  { title: "A People's Guide to Capitalism", genre: "", priority: "" },
  { title: "Unruly", genre: "", priority: "" },
  { title: "One Up on Wall Street by Lynch", genre: "", priority: "" },
  { title: "The Lucky Ones", genre: "", notes: "India", priority: "" },
  { title: "Rabbit Books by Updike", genre: "", priority: "" },
  { title: "Aubrey Maturin", genre: "", priority: "" },
  { title: "My Secret Garden", genre: "", priority: "" },
  { title: "Red Rising", genre: "", priority: "" },
  { title: "There Are Rivers in the Sky", genre: "", priority: "" },
  { title: "Londoners by Craig Taylor", genre: "", priority: "" },
  { title: "Rise to Globalism", genre: "", priority: "" },
  { title: "John Gunther", genre: "", priority: "" },
  { title: "How to Stand Up to a Dictator", genre: "", priority: "" },
  { title: "What Makes Sammy Run", genre: "", priority: "" },
  { title: "One Soldier's War", genre: "", priority: "" },
  { title: "Men to Match My Mountains", genre: "", notes: "Munger", priority: "" },
  { title: "Deep Simplicity", genre: "", notes: "Munger", priority: "" },
  { title: "Ice Age by Gribbin", genre: "", notes: "Munger", priority: "" },
  { title: "How the Scots Invented the Modern World", genre: "", notes: "Munger", priority: "" },
  { title: "The Third Chimpanzee", genre: "", notes: "Munger", priority: "" },
  { title: "Men and Rubber", genre: "", notes: "Munger", priority: "" },
  { title: "Social Origins of Dictatorship and Democracy", genre: "", priority: "" },
  { title: "New Cold Wars", genre: "", priority: "" },
  { title: "Age of Revolutions", genre: "", priority: "" },
  { title: "The Gift of Fear", genre: "", priority: "" },
  { title: "Walk the Blue Line", genre: "", priority: "" },
  { title: "The Worm at the Core", genre: "", priority: "" },
  { title: "The Luxury Strategy", genre: "", priority: "" },
  { title: "Skunk Works", genre: "", priority: "" },
  { title: "Count of Monte Cristo", genre: "", priority: "" },
  { title: "The Naked Don't Fear the Water", genre: "", priority: "" },
  { title: "Surrender or Starve", genre: "", priority: "" },
  { title: "A House in the Sky", genre: "", priority: "" },
  { title: "Cold War by Gaddis", genre: "", priority: "" },
  { title: "Cold War by Westad", genre: "", priority: "" },
  { title: "The Rebel", genre: "", priority: "" },
  { title: "The Spinoza Problem", genre: "", priority: "" },
  { title: "The Schopenhauer Cure", genre: "", priority: "" },
  { title: "Lonesome Dove", genre: "", priority: "" },
  { title: "Whiteout", genre: "", priority: "" },
  { title: "What It Takes", genre: "", priority: "" },
  { title: "Madame Bovary", genre: "", priority: "" },
  { title: "Constellation of Vital Phenomenon", genre: "", priority: "" },
  { title: "Noonday Demon", genre: "", priority: "" },
  { title: "Thinking in Time", genre: "", priority: "" },
  { title: "The Tangled Wing", genre: "", priority: "" },
  { title: "The Culture Map", genre: "", priority: "" },
  { title: "The Oligarchs", genre: "", priority: "" },
  { title: "The Dawn of Everything", genre: "", priority: "" },
  { title: "Love's Executioner", genre: "", priority: "" },
  { title: "Bloodlands", genre: "", priority: "" },
  { title: "Blood and Ruins", genre: "", priority: "" },
  { title: "The Scandinavians by Connery", genre: "", priority: "" },
  { title: "Do Not Disturb", genre: "", notes: "Kagame", priority: "" },
  { title: "We Are Bellingcat", genre: "", priority: "" },
  { title: "OSINT by Michael Bazzell", genre: "", priority: "" },
  { title: "The Gun, the Ship, and the Pen", genre: "", priority: "" },
  { title: "Mr Putin: Operative in the Kremlin", genre: "", priority: "" },
  { title: "The Sovereign Individual", genre: "", priority: "" },
  { title: "Six Easy Pieces", genre: "", priority: "" },
  { title: "Buy Then Build", genre: "", priority: "" },
  { title: "HBR Guide to Buying a Small Business", genre: "", priority: "" },
  { title: "Managing a Nonprofit Organization", genre: "", priority: "" },
  { title: "Great Books of the Western World", genre: "", priority: "" },
  { title: "Arnold Toynbee Abridgments", genre: "History/War", notes: "world history", priority: "" },
  { title: "The Secret of Our Success", genre: "Culture/Society", pages: 464, priority: "" },
  { title: "The Politics Industry", genre: "Politics", pages: 272, priority: "" },
  { title: "How to Change Your Mind", genre: "Crime/Drugs", pages: 480, notes: "psychedelics", priority: "" },
  { title: "Americans: The National Experience", genre: "History/War", pages: 528, priority: "" },
  { title: "Manufacturing Consent", genre: "Culture/Society", priority: "" },
  { title: "Big Chicken", genre: "Culture/Society", priority: "" },
  { title: "Why Nations Fail", genre: "Politics", pages: 544, priority: "" },
  { title: "How to Hide an Empire", genre: "History/War", priority: "" },
  { title: "Network Propaganda", genre: "Politics", notes: "Disinformation", priority: "" },
  { title: "Legacy of Ashes", genre: "History/War", notes: "History of CIA", priority: "" },
  { title: "These Truths", genre: "", priority: "" },
  { title: "Against the Gods: The Remarkable Story of Risk", genre: "", priority: "" },
  { title: "Anarchy, State, and Utopia", genre: "", priority: "" },
  { title: "Al Franken Giant of the Senate", genre: "", priority: "" },
  { title: "Boss: Richard J Daley", genre: "", priority: "" },
  { title: "The Art of Thinking Clearly", genre: "", priority: "" },
  { title: "The Broken Ladder", genre: "", priority: "" },
  { title: "Evicted: Poverty and Profit in the American City", genre: "", priority: "" },
  { title: "The Empire Project", genre: "", priority: "" },
  { title: "The Republic of Suffering", genre: "", priority: "" },
  { title: "Divided by God", genre: "", priority: "" },
  { title: "The Right Stuff", genre: "", priority: "" },
  { title: "The Electric Kool-Aid Acid Test", genre: "", priority: "" },
  { title: "A Man in Full", genre: "", priority: "" },
  { title: "Cheerful Money", genre: "", priority: "" },
  { title: "Mine!", genre: "", priority: "" },
  { title: "Empire of Pain", genre: "", priority: "" },
  { title: "Way Worse Than Being a Dentist", genre: "", priority: "" },
  { title: "Lost Connections", genre: "", priority: "" },
  { title: "Newjack", genre: "", priority: "" },
  { title: "Spirit of Place by Lawrence Durrell", genre: "", priority: "" },
  { title: "The Story of Christianity", genre: "", priority: "" },
  { title: "How the Catholic Church Built Western Civilization", genre: "", priority: "" },
  { title: "In Praise of Slowness", genre: "", priority: "" },
  { title: "Paganism by Higginbotham", genre: "", priority: "" },
  { title: "The Anglo Saxon World", genre: "", notes: "England", priority: "" },
  { title: "The Norman Conquest by Morris", genre: "", notes: "England", priority: "" },
  { title: "The Boundless Sea", genre: "", notes: "Ocean", priority: "" },
  { title: "The Napoleonic Wars: A Global History", genre: "", priority: "" },
  { title: "Countdown to Zero", genre: "", notes: "stuxnet", priority: "" },
  { title: "Expeditions Unpacked", genre: "", priority: "" },
  { title: "Cod", genre: "", notes: "New England", priority: "" },
  { title: "Work: A Deep History, from the Stone Age to the Age of Robots", genre: "", priority: "" },
  { title: "Amazon Unbound: Jeff Bezos and the Invention of a Global Empire", genre: "", priority: "" },
  { title: "Inglorious Empire", genre: "", notes: "India", priority: "" },
  { title: "India After Gandhi", genre: "", notes: "India", priority: "" },
  { title: "Survival of the Prettiest", genre: "", priority: "" },
  { title: "The Color of Law", genre: "", priority: "" },
  { title: "Seize the Time: The Story of the Black Panther Party", genre: "", priority: "" },
  { title: "Say Nothing", genre: "", priority: "" },
  { title: "Oxford History of the United States", genre: "", priority: "" },
  { title: "California: A History", genre: "", priority: "" },
  { title: "A History of the American People", genre: "", priority: "" },
  { title: "1776 by David McCullough", genre: "", priority: "" },
  { title: "Invisible Countries", genre: "", priority: "" },
  { title: "100 Ways to Improve Your Writing", genre: "", priority: "" },
  { title: "Silicon City San Francisco Shadow", genre: "", priority: "" },
  { title: "American Nomads", genre: "", priority: "" },
  { title: "Fortunate Son by Fogerty", genre: "", priority: "" },
  { title: "The Bonfire of the Vanities", genre: "", priority: "" },
  { title: "Christianity the First Three Thousand Years", genre: "", priority: "" },
  { title: "Collapse of Complex Societies", genre: "", priority: "" },
  { title: "Blood and Oil", genre: "", priority: "" },
  { title: "Barbarian Days", genre: "", priority: "" },
  { title: "Only Yesterday", genre: "", priority: "" },
  { title: "Fooled by Randomness", genre: "", priority: "" },
  { title: "The Body: A Guide for Occupants", genre: "Evolution/Biology/Nature", notes: "Bill Bryson", priority: "" },
  { title: "Hard Times", genre: "History/War", pages: 480, notes: "Great depression", priority: "" },
  { title: "Becoming a Writer", genre: "Philosophy/Life Improvement", priority: "" },
  { title: "Warmth of Other Suns", genre: "History/War", notes: "Black migration", priority: "1" },
  { title: "America's Bank", genre: "History/War", priority: "" },
  { title: "A Splendid Exchange", genre: "History/War", priority: "" },
  { title: "The Stages of Economic Growth", genre: "Business/Economics", priority: "" },
  { title: "The Ascent of Man", genre: "History/War", priority: "" },
  { title: "The Wonder That Was India", genre: "History/War", notes: "India", priority: "" },
  { title: "Leaving the Atocha Station", genre: "Fiction", priority: "" },
  { title: "Figure Drawing for All It's Worth", genre: "Religion/Art", priority: "" },
  { title: "Figure Drawing: Design and Invention", genre: "Religion/Art", priority: "" },
  { title: "Figure Drawing: A Complete Guide", genre: "Religion/Art", priority: "" },
  { title: "Figure Drawing Studio", genre: "Religion/Art", priority: "" },
  { title: "Drawing the Female Nude", genre: "Religion/Art", priority: "" },
  { title: "What It Takes: The Way to the White House", genre: "Politics", pages: 1738, notes: "1988 Election", priority: "" },
  { title: "Dispatches", genre: "History/War", pages: 274, notes: "Vietnam", priority: "" },
  { title: "Slouching Towards Bethlehem", genre: "Culture/Society", pages: 256, notes: "SF in the 60s", priority: "" },
  { title: "The Omnivore's Dilemma", genre: "Culture/Society", pages: 468, notes: "Food choices", priority: "" },
  { title: "Travels in the Interior of Africa", genre: "Travel/Adventure", pages: 125, notes: "1799 Africa travel book", priority: "" },
  { title: "Goodbye to All That", genre: "History/War", pages: 347, notes: "Trenches in WWI", priority: "" },
  { title: "The Road to Wigan Pier", genre: "Culture/Society", pages: 226, notes: "Orwell on poverty", priority: "" },
  { title: "The Nude: A Study in Ideal Form", genre: "Religion/Art", pages: 481, priority: "" },
  { title: "The Man Who Mistook His Wife for a Hat", genre: "Evolution/Biology/Nature", pages: 256, notes: "Stories about crazy people", priority: "" },
  { title: "Surely You're Joking Mr. Feynman", genre: "Biography/Memoir", pages: 400, notes: "Biography", priority: "" },
  { title: "Burn Math Class", genre: "Math/Other Science", pages: 400, priority: "" },
  { title: "So You've Been Publicly Shamed", genre: "Culture/Society", pages: 336, priority: "" },
  { title: "Robert Caro LBJ", genre: "Biography/Memoir", pages: 4613, priority: "" },
  { title: "The Geography of Nowhere", genre: "Culture/Society", pages: 304, notes: "Urban planning", priority: "" },
  { title: "Asimov's Guide to the Bible", genre: "Religion/Art", pages: 1295, priority: "" },
  { title: "Goliath", genre: "Business/Economics", pages: 352, notes: "The 100-Year War Between Monopoly Power and Democracy", priority: "" },
  { title: "The Unwinding", genre: "Culture/Society", pages: 448, notes: "Book about everyday America", priority: "" },
  { title: "Kissinger Diplomacy", genre: "History/War", pages: 912, priority: "" },
  { title: "Battle Cry of Freedom", genre: "History/War", pages: 909, notes: "Civil War", priority: "" },
  { title: "Judgement in Managerial Decision Making", genre: "Business/Economics", pages: 288, priority: "" },
  { title: "Sources of Power", genre: "Psychology/Behaviorial Econ", pages: 338, priority: "" },
  { title: "Until the End of Time", genre: "Math/Other Science", pages: 448, priority: "" },
  { title: "High Output Management", genre: "Business/Economics", pages: 272, priority: "" },
  { title: "The Wisdom of Crowds", genre: "Psychology/Behaviorial Econ", pages: 336, priority: "" },
  { title: "Misbehaving", genre: "Psychology/Behaviorial Econ", pages: 432, priority: "" },
  { title: "Believing Brain", genre: "Psychology/Behaviorial Econ", pages: 385, priority: "1" },
  { title: "Our Man in Havana", genre: "Fiction", pages: 273, priority: "" },
  { title: "MBS", genre: "Politics", pages: 384, notes: "Saudi", priority: "" },
  { title: "Good Reasons for Bad Feelings", genre: "Psychology/Behaviorial Econ", pages: 383, notes: "Economist Rec", priority: "" },
  { title: "Narrative Economics", genre: "Psychology/Behaviorial Econ", pages: 400, notes: "Economist Rec", priority: "" },
  { title: "Good Economics for Hard Times", genre: "Business/Economics", pages: 432, notes: "Economist Rec", priority: "" },
  { title: "How to Be a Dictator", genre: "Politics", pages: 304, notes: "Economist Rec", priority: "" },
  { title: "Dignity: Seeking Respect in Back Row America", genre: "Culture/Society", pages: 304, notes: "Economist Rec", priority: "" },
  { title: "The Man Who Solved the Market", genre: "Biography/Memoir", pages: 384, notes: "Economist Rec", priority: "" },
  { title: "In Defense of Elitism", genre: "Culture/Society", pages: 336, priority: "" },
  { title: "The World: A Brief Introduction", genre: "Politics", pages: 400, notes: "President of CFR", priority: "1" },
  { title: "Papillon", genre: "Fiction", pages: 576, priority: "" },
  { title: "Mastermind: The Many Faces of 9/11", genre: "History/War", pages: 290, priority: "" },
  { title: "Why Torture Doesn't Work", genre: "History/War", pages: 336, priority: "" },
  { title: "An American Caddie in St. Andrews", genre: "Biography/Memoir", pages: 352, priority: "" },
  { title: "Chekhov The Little Trilogy", genre: "Fiction", pages: 86, priority: "" },
  { title: "The Fixer: My Adventures Saving Startups from Death by Politics", genre: "Politics", pages: 256, notes: "Founder of Tusk", priority: "" },
  { title: "A History of God", genre: "Religion/Art", pages: 496, priority: "" },
  { title: "Jim Rogers Street Smarts", genre: "Business/Economics", pages: 272, priority: "" },
  { title: "Show, Don't Tell", genre: "Philosophy/Life Improvement", pages: 114, notes: "Writing book", priority: "" },
  { title: "The Secret Lives of Color", genre: "Religion/Art", pages: 320, priority: "" },
  { title: "The Buried: Archaeology of the Egyptian Revolution", genre: "Politics", pages: 480, priority: "" },
  { title: "The Death and Life of Great American Cities", genre: "Culture/Society", pages: 458, priority: "" },
  { title: "In Extremis", genre: "Biography/Memoir", pages: 400, notes: "About war correspondent", priority: "" },
  { title: "Hawaii", genre: "Fiction", pages: 937, notes: "Michener", priority: "" },
  { title: "Complete Short Stories of Ernest Hemingway", genre: "Fiction", pages: 650, priority: "" },
  { title: "Out of Africa", genre: "Fiction", pages: 416, priority: "" },
  { title: "Nile Tributaries of Abyssinia", genre: "Fiction", pages: 352, notes: "Hemingway Rec", priority: "" },
  { title: "Zen in the Art of Writing", genre: "Philosophy/Life Improvement", pages: 158, priority: "" },
  { title: "Essential English for Journalists", genre: "Philosophy/Life Improvement", pages: 256, priority: "" },
  { title: "Bottle of Lies", genre: "Crime/Drugs", pages: 512, notes: "Counterfeit drugs", priority: "" },
  { title: "The Making of the President", genre: "Politics", pages: 400, notes: "1960 Election", priority: "" },
  { title: "The Gulf: The Making of an American Sea", genre: "History/War", pages: 608, priority: "" },
  { title: "Spillover", genre: "Evolution/Biology/Nature", pages: 592, notes: "Medicine/Disease", priority: "" },
  { title: "The Signal and the Noise", genre: "Math/Other Science", pages: 560, priority: "" },
  { title: "Sea Power: The History and Geopolitics", genre: "History/War", pages: 384, notes: "Pajaro/Ocean", priority: "" },
  { title: "Pacific: Silicon Chips and Surfboards", genre: "History/War", pages: 512, notes: "Pajaro/Ocean", priority: "" },
  { title: "The English and Their History", genre: "History/War", pages: 1040, notes: "England", priority: "" },
  { title: "The Italians", genre: "Culture/Society", pages: 336, notes: "Italy", priority: "" },
  { title: "How to Fail at Almost Everything and Still Win Big", genre: "Philosophy/Life Improvement", pages: 247, priority: "" },
  { title: "The Prophet", genre: "Philosophy/Life Improvement", pages: 128, priority: "" },
  { title: "Total Freedom: The Essential Krishnamurti", genre: "Philosophy/Life Improvement", pages: 384, priority: "" },
  { title: "Genome", genre: "Evolution/Biology/Nature", pages: 368, priority: "" },
  { title: "Passport to Profits", genre: "Business/Economics", pages: 432, priority: "" },
  { title: "Secrets of Closing the Sale", genre: "Business/Economics", pages: 432, priority: "" },
  { title: "Pattern Recognition", genre: "Fiction", pages: 384, priority: "" },
  { title: "Debt: The First 5000 Years", genre: "Business/Economics", pages: 560, priority: "" },
  { title: "Awareness: The Perils and Opportunities of Reality", genre: "Philosophy/Life Improvement", pages: 184, priority: "" },
  { title: "The Four Hour Chef", genre: "Philosophy/Life Improvement", pages: 672, priority: "" },
  { title: "The Refusal of Work", genre: "Philosophy/Life Improvement", pages: 224, priority: "" },
  { title: "Origin of Species", genre: "Evolution/Biology/Nature", pages: 576, priority: "" },
  { title: "Letters from a Stoic", genre: "Philosophy/Life Improvement", pages: 254, priority: "" },
  { title: "Poor Charlie's Almanac", genre: "Business/Economics", pages: 548, priority: "" },
  { title: "Game Change", genre: "Politics", pages: 456, notes: "2008 Election", priority: "" },
  { title: "The Rebel Allocator", genre: "Fiction", pages: 268, priority: "" },
  { title: "The Red Queen", genre: "Evolution/Biology/Nature", pages: 416, notes: "Sex", priority: "" },
  { title: "Perfectly Reasonable Deviations from the Beaten Track", genre: "Philosophy/Life Improvement", pages: 512, priority: "" },
  { title: "Barking Up the Wrong Tree", genre: "Philosophy/Life Improvement", pages: 320, priority: "" },
  { title: "Wampeters, Foma & Granfalloons", genre: "Fiction", pages: 288, notes: "Vonnegut", priority: "" },
  { title: "There Was a Country", genre: "Biography/Memoir", pages: 352, notes: "Africa - Achebe", priority: "" },
  { title: "Black Like Me", genre: "Culture/Society", pages: 208, notes: "US History", priority: "" },
  { title: "The Little Book of Valuation", genre: "Business/Economics", pages: 256, priority: "" },
  { title: "McKinsey Valuation", genre: "Business/Economics", pages: 848, priority: "" },
  { title: "The Political Campaign Desk Reference", genre: "Politics", pages: 278, priority: "" },
  { title: "Educated: A Memoir", genre: "Culture/Society", pages: 352, priority: "" },
  { title: "The Top Five Regrets of the Dying", genre: "Philosophy/Life Improvement", pages: 247, priority: "" },
  { title: "When Nietzsche Wept", genre: "Fiction", pages: 353, notes: "Adrien rec", priority: "" },
  { title: "How to Avoid Being Killed in a War Zone", genre: "Travel/Adventure", pages: 304, priority: "" },
  { title: "#BreakIntoVC", genre: "Business/Economics", pages: 170, notes: "Venture", priority: "" },
  { title: "Fallen Leaves", genre: "Philosophy/Life Improvement", pages: 208, notes: "Durant's Musings", priority: "" },
  { title: "This Life", genre: "Religion/Art", pages: 464, notes: "Secular Faith", priority: "" },
  { title: "One L", genre: "Culture/Society", pages: 304, notes: "Harvard Law", priority: "" },
  { title: "7 Powers", genre: "Business/Economics", pages: 210, notes: "Business Strategy", priority: "" },
  { title: "Never Split the Difference", genre: "Business/Economics", pages: 288, notes: "Negotiations", priority: "" },
  { title: "Maps of War", genre: "History/War", pages: 224, priority: "" },
  { title: "Tribal Leadership", genre: "Business/Economics", pages: 303, priority: "" },
  { title: "The Life and Times of the Thunderbolt Kid", genre: "Biography/Memoir", pages: 270, notes: "Bryson", priority: "" },
  { title: "Absent Superpower", genre: "Politics", pages: 422, priority: "" },
  { title: "Accidental Superpower", genre: "Politics", pages: 384, priority: "" },
  { title: "Against Democracy", genre: "Politics", pages: 312, priority: "" },
  { title: "The Whole Shebang", genre: "Math/Other Science", pages: 393, notes: "Astronomy", priority: "" },
  { title: "The Unbearable Lightness of Being", genre: "Fiction", pages: 320, priority: "1" },
  { title: "African Kaiser", genre: "History/War", pages: 448, priority: "" },
  { title: "The Count of Monte Cristo", genre: "Fiction", pages: 1276, priority: "" },
  { title: "Sirens of Titan", genre: "Fiction", pages: 336, priority: "" },
  { title: "How to Turn Down a Billion Dollars", genre: "Business/Economics", pages: 304, notes: "Snapchat", priority: "" },
  { title: "The Crucible", genre: "Fiction", pages: 160, notes: "Arthur Miller", priority: "" },
  { title: "Chimpanzee Politics", genre: "Evolution/Biology/Nature", pages: 256, priority: "" },
  { title: "The Bonobo and the Atheist", genre: "Evolution/Biology/Nature", pages: 320, priority: "" },
  { title: "Plunkitt of Tammany Hall", genre: "Politics", pages: 128, priority: "" },
  { title: "Burmese Days", genre: "Fiction", pages: 288, priority: "" },
  { title: "The Storm Before the Storm", genre: "History/War", pages: 352, notes: "Italy", priority: "" },
  { title: "As I Walked Out One Midsummer Morning", genre: "Travel/Adventure", pages: 216, notes: "Spanish Civil War", priority: "" },
  { title: "The Shallows", genre: "Psychology/Behavioral Econ", pages: 289, notes: "Effect of internet on brain", priority: "" },
  { title: "Predictably Irrational", genre: "Psychology/Behavioral Econ", pages: 380, priority: "" },
  { title: "The Power of Habit", genre: "Psychology/Behavioral Econ", pages: 416, priority: "" },
  { title: "Churchill and Orwell", genre: "History/War", pages: 352, priority: "" },
  { title: "On Human Nature", genre: "Evolution/Biology/Nature", pages: 288, priority: "" },
  { title: "Beyond Religion", genre: "Religion/Art", pages: 208, priority: "" },
  { title: "Sociobiology", genre: "Evolution/Biology/Nature", pages: 697, priority: "" },
  { title: "The China Study", genre: "Culture/Society", pages: 417, priority: "" },
  { title: "Mindfulness: A Practical Guide", genre: "Math/Other Science", pages: 288, priority: "" },
  { title: "The Invention of Nature", genre: "Evolution/Biology/Nature", pages: 496, priority: "" },
  { title: "The Lucifer Effect", genre: "Psychology/Behaviorial Econ", pages: 551, priority: "" },
  { title: "The Rebel by Camus", genre: "Fiction", pages: 320, priority: "" },
  { title: "Reeves Kennedy", genre: "Politics", pages: 800, priority: "" },
  { title: "Storm of Steel", genre: "History/War", pages: 320, priority: "" },
  { title: "Guns of August", genre: "History/War", pages: 511, priority: "" },
  { title: "Goodbye Things", genre: "Philosophy/Life Improvement", pages: 272, priority: "" },
  { title: "Notes on a Foreign Country", genre: "Travel/Adventure", pages: 288, priority: "" },
  { title: "Origins of Political Order", genre: "Politics", pages: 606, priority: "1" },
  { title: "The Brain That Changes Itself", genre: "Psychology/Behaviorial Econ", pages: 447, priority: "" },
  { title: "Survivors of Stalingrad", genre: "History/War", pages: 288, priority: "" },
  { title: "An Infantryman in Stalingrad", genre: "History/War", pages: 250, priority: "" },
  { title: "Matterhorn: A Novel of the Vietnam War", genre: "History/War", pages: 600, priority: "" },
  { title: "What Is It Like to Go to War", genre: "History/War", pages: 272, priority: "" },
  { title: "Nudge", genre: "Psychology/Behaviorial Econ", pages: 320, priority: "" },
  { title: "The Undoing Project", genre: "Psychology/Behaviorial Econ", pages: 368, priority: "" },
  { title: "Why Is Sex Fun?", genre: "Psychology/Behaviorial Econ", pages: 179, priority: "" },
  { title: "McMafia", genre: "Crime/Drugs", pages: 529, priority: "" },
  { title: "Beyond Good and Evil", genre: "Philosophy/Life Improvement", pages: 154, priority: "" },
  { title: "Genealogy of Morals", genre: "Philosophy/Life Improvement", pages: 208, priority: "" },
  { title: "Travel Guides (Nepal) Lonely Planet", genre: "Travel/Adventure", pages: 408, priority: "" },
  { title: "A History of Strategy: From Sun Tzu to William S. Lind", genre: "History/War", priority: "" },
  { title: "Fate Is the Hunter", genre: "Travel/Adventure", pages: 416, notes: "Pilot book", priority: "" },
  { title: "Why the West Rules, For Now", genre: "History/War", pages: 976, priority: "" },
  { title: "Strangers in Their Own Land", genre: "Culture/Society", notes: "Angry Whites", priority: "" },
  { title: "The Better Angels of Our Nature", genre: "Psychology/Behaviorial Econ", pages: 844, priority: "" },
  { title: "The Anatomy of Violence", genre: "Psychology/Behaviorial Econ", pages: 496, notes: "Biology of crime", priority: "" },
  { title: "On Politics", genre: "Politics", pages: 1152, notes: "Political philosophy/history", priority: "1" },
  { title: "SPQR: A History of Ancient Rome", genre: "History/War", notes: "Italy", priority: "" },
  { title: "Blink", genre: "Psychology/Behaviorial Econ", priority: "" },
  { title: "The Gene: An Intimate History", genre: "Evolution/Biology/Nature", priority: "" },
  { title: "At Home by Bryson", genre: "Culture/Society", priority: "" },
  { title: "How to Lie with Statistics", genre: "", priority: "" },
  { title: "Zen and the Art of Motorcycle Maintenance", genre: "Philosophy/Life Improvement", priority: "" },
  { title: "Age of Ambition", genre: "Politics", pages: 417, notes: "China", priority: "" },
  { title: "The Miracle of Theism", genre: "Religion/Art", priority: "" },
  { title: "Righteous Mind", genre: "Psychology/Behaviorial Econ", pages: 530, notes: "Why Good People Are Divided by Politics and Religion", priority: "" },
  { title: "Antifragile", genre: "Math/Other Science", pages: 519, notes: "Things that Gain from Disorder", priority: "" },
  { title: "The Human Condition", genre: "Philosophy/Life Improvement", pages: 370, notes: "Hannah Arendt", priority: "" },
  { title: "Forgotten Soldier", genre: "Biography/Memoir", pages: 508, notes: "Fighting on Eastern Front", priority: "" },
  { title: "Currency Wars: The Making of the Next Global Crisis", genre: "Business/Economics", pages: 320, priority: "" },
  { title: "Painted Wolves: A Wild Dogs Life", genre: "Evolution/Biology/Nature", priority: "" },
  { title: "21 Lessons for the 21st Century", genre: "Politics", priority: "" },
  { title: "Solitary Fitness", genre: "Philosophy/Life Improvement", priority: "" },
  { title: "Dancing in the Glory of Monsters", genre: "History/War", pages: 418, notes: "Congo", priority: "2" },
  { title: "The Great Influenza", genre: "History/War", pages: 562, notes: "The Story of the Deadliest Pandemic in History", priority: "1" },
  { title: "The Imperial Archive", genre: "History/War", pages: 188, priority: "" },
  { title: "The Third Chimpanzee", genre: "Evolution/Biology/Nature", pages: 432, notes: "The Evolution and Future of the Human Animal", priority: "" },
  { title: "The War Nerd Iliad", genre: "History/War", priority: "" },
  { title: "A History of the World in Six Glasses", genre: "Culture/Society", pages: 336, priority: "" },
  { title: "The Red Atlas", genre: "Religion/Art", notes: "Soviet Maps", priority: "" },
  { title: "Great Maps", genre: "Religion/Art", priority: "" },
  { title: "Flash Boys", genre: "Business/Economics", pages: 179, notes: "Michael Lewis", priority: "" },
  { title: "Corruption: A Very Short Introduction", genre: "Politics", pages: 169, priority: "" },
  { title: "The Tangled Wing", genre: "Evolution/Biology/Nature", pages: 580, notes: "Biological Constraints on the Human Spirit", priority: "" },
  { title: "Nostromo", genre: "Fiction", priority: "" },
  { title: "The Quiet American", genre: "Fiction", notes: "Vietnam 1955", priority: "" },
  { title: "The Grand Chessboard", genre: "Politics", pages: 240, priority: "" },
  { title: "My Struggle", genre: "Biography/Memoir", priority: "" },
  { title: "D-Day Through German Eyes", genre: "History/War", pages: 330, priority: "" },
  { title: "Sex on Show Seeing the Erotic", genre: "Evolution/Biology/Nature", priority: "" },
  { title: "A History of the World in Bite Sized Chunks", genre: "History/War", priority: "" },
  { title: "Art: The Whole Story", genre: "Religion/Art", priority: "" },
  { title: "British Embassies", genre: "Religion/Art", priority: "" },
  { title: "Churchill: The Second World War", genre: "History/War", priority: "" },
  { title: "Born Fighting", genre: "Culture/Society", notes: "Scots Irish", priority: "" },
  { title: "Little Wars by HG Wells", genre: "Culture/Society", pages: 98, priority: "" },
  { title: "The Road to Kalamata", genre: "History/War", priority: "" },
  { title: "My Reminisces of East Africa", genre: "History/War", priority: "" },
  { title: "Chasing the Scream", genre: "Crime/Drugs", notes: "War on Drugs", priority: "" },
  { title: "American Holocaust", genre: "History/War", priority: "" },
  { title: "Abundance", genre: "Culture/Society", pages: 400, notes: "The Future Is Better Than You Think", priority: "" },
  { title: "Stiff", genre: "Culture/Society", pages: 304, priority: "" },
  { title: "Command and Control", genre: "Culture/Society", pages: 656, notes: "Management of US Nukes", priority: "" },
  { title: "Uncommon Carriers", genre: "Culture/Society", pages: 256, notes: "People in the transport biz", priority: "" },
  { title: "Boorstin: The Discoverers", genre: "Culture/Society", pages: 770, notes: "History of Knowledge", priority: "" },
  { title: "A People's History of the United States", genre: "History/War", priority: "" },
  { title: "Lonely Planets", genre: "Travel/Adventure", priority: "" },
  { title: "Beevor: The Second World War", genre: "History/War", priority: "" },
  { title: "The Decline and Fall of Practically Everybody", genre: "Biography/Memoir", pages: 240, notes: "A very funny view of famous people throughout history", priority: "" },
  { title: "Undaunted Courage", genre: "Biography/Memoir", notes: "Lewis and Clark", priority: "" },
  { title: "A Pattern Language", genre: "Culture/Society", pages: 1171, notes: "Towns, Building, Construction", priority: "" },
  { title: "The World's Religions by Huston Smith", genre: "Religion/Art", pages: 450, priority: "2" },
  { title: "Empire of the Deep", genre: "History/War", pages: 675, notes: "The Rise and Fall of the British Navy", priority: "" },
  { title: "The Worst Hard Time", genre: "History/War", pages: 340, notes: "The Untold Story of Those Who Survived the Great American Dust Bowl", priority: "" },
  { title: "Confessions of an English Opium Eater", genre: "Biography/Memoir", pages: 340, notes: "Addiction narrative", priority: "" },
  { title: "Carnage and Culture", genre: "History/War", pages: 544, notes: "Various battles", priority: "" },
  { title: "The Great War for Civilization", genre: "History/War", pages: 1397, notes: "A sweeping and dramatic history of the last half century of conflict in the Middle East", priority: "" },
  { title: "From Dawn to Decadence: 1500 to the Present", genre: "Culture/Society", pages: 912, notes: "A stunning five-century study of civilization's cultural retreat", priority: "" },
  { title: "The Disappearing Spoon", genre: "Math/Other Science", pages: 416, notes: "History of elements - chemistry", priority: "" },
  { title: "Salt: A World History", genre: "History/War", pages: 496, priority: "2" },
  { title: "The Etymologicon", genre: "Culture/Society", pages: 304, notes: "A Circular Stroll Through the Hidden Connections of the English Language", priority: "" },
  { title: "What I Eat: Around the World in 80 Diets", genre: "Culture/Society", priority: "" },
  { title: "At Home With Books", genre: "Culture/Society", priority: "" },
  { title: "Appetites: A Cookbook", genre: "Philosophy/Life Improvement", pages: 304, notes: "Anthony Bourdain", priority: "2" },
  { title: "The River War", genre: "History/War", pages: 274, notes: "Churchill - Conquest of Sudan", priority: "" },
  { title: "Seven Pillars of Wisdom", genre: "History/War", pages: 819, notes: "Lawrence of Arabia", priority: "" },
  { title: "Gates of Fire", genre: "Fiction", pages: 525, notes: "Novel About Thermopylae", priority: "" },
  { title: "Capitol Punishment", genre: "Politics", pages: 303, notes: "Lobbying - Jack Abramoff", priority: "" },
  { title: "Dispatches from Pluto", genre: "Culture/Society", pages: 322, notes: "Mississippi", priority: "" },
  { title: "The Deepest South of All", genre: "Culture/Society", pages: 288, notes: "Mississippi", priority: "" },
  { title: "God's Middle Finger", genre: "Travel/Adventure", pages: 288, notes: "Modern Mexican Frontier", priority: "" },
  { title: "On Combat", genre: "Psychology/Behaviorial Econ", pages: 403, notes: "The Psychology and Physiology of Deadly Conflict in War and in Peace", priority: "" },
  { title: "Robinson Crusoe", genre: "Fiction", priority: "" },
  { title: "Steppenwolf", genre: "Fiction", priority: "" },
  { title: "Road to Serfdom", genre: "Business/Economics", pages: 296, priority: "" },
  { title: "Spain in Our Hearts by Adam Hochschild", genre: "History/War", priority: "" },
  { title: "The Looming Tower", genre: "History/War", pages: 540, notes: "Al Qaeda and the road to 9/11", priority: "" },
  { title: "The Age of Wonder", genre: "History/War", pages: 600, notes: "How the Romantic Generation Discovered the Beauty and Terror of Science", priority: "" },
  { title: "How We Die", genre: "Philosophy/Life Improvement", pages: 306, priority: "" },
  { title: "Shop Class as Soulcraft", genre: "Philosophy/Life Improvement", priority: "" },
  { title: "Life", genre: "Religion/Art", pages: 576, notes: "Keith Richards/Rolling Stones", priority: "" },
  { title: "Exodus", genre: "History/War", pages: 610, notes: "Israel", priority: "" },
  { title: "All Quiet on the Western Front", genre: "Fiction", pages: 240, priority: "" },
  { title: "The Black Hand", genre: "Crime/Drugs", pages: 332, notes: "The Bloody Rise and Redemption of Boxer Enriquez, a Mexican Mob Killer", priority: "" },
  { title: "The Myth of the Rational Voter", genre: "Politics", pages: 296, priority: "" },
  { title: "You Are Not So Smart", genre: "Psychology/Behaviorial Econ", pages: 320, priority: "" },
  { title: "On War", genre: "History/War", pages: 753, notes: "Clausewitz", priority: "" },
  { title: "Art of War", genre: "History/War", priority: "" },
  { title: "The Complete Calvin and Hobbes", genre: "Fiction", priority: "" },
  { title: "Journeys of a Lifetime", genre: "Travel/Adventure", priority: "" },
  { title: "Devils Guard", genre: "History/War", pages: 336, notes: "French Foreign Legion in Indochina", priority: "" },
  { title: "Legionnaire: An Englishman in the French Foreign Legion", genre: "Biography/Memoir", pages: 320, priority: "" },
  { title: "The Black Book of Communism", genre: "Politics", pages: 858, notes: "Anti Communism", priority: "" },
  { title: "Angela's Ashes", genre: "Fiction", pages: 364, notes: "Ireland", priority: "" },
  { title: "Song of the Dodo", genre: "Evolution/Biology/Nature", pages: 704, notes: "Island Biogeography in an Age of Extinction", priority: "" },
  { title: "Blood Meridian", genre: "Fiction", priority: "" },
  { title: "How Everything Became War", genre: "Politics", pages: 448, priority: "" },
  { title: "Soldier and the State", genre: "History/War", pages: 560, notes: "Huntington - The Theory and Politics of Civil-Military Relations", priority: "" },
  { title: "Darkness at Noon", genre: "Fiction", pages: 272, priority: "2" },
  { title: "Inside a U.S. Embassy", genre: "Politics", pages: 282, priority: "" },
  { title: "No Place to Hide", genre: "Politics", pages: 300, notes: "Edward Snowden, the NSA, and the U.S. Surveillance State", priority: "" },
  { title: "Cultures and Organizations: Software of the Mind", genre: "Psychology/Behaviorial Econ", pages: 577, priority: "2" },
  { title: "The Dictator's Handbook", genre: "Politics", pages: 352, priority: "" },
  { title: "The Way of the Knife", genre: "History/War", pages: 400, priority: "" },
  { title: "Doors of Perception, Heaven and Hell", genre: "Crime/Drugs", pages: 100, notes: "Huxley", priority: "" },
  { title: "Hemingway on Hunting", genre: "Travel/Adventure", pages: 340, priority: "" },
  { title: "Evolutionary Psychology: A Beginner's Guide", genre: "Evolution/Biology/Nature", pages: 240, priority: "3" },
  { title: "The Salmon of Doubt", genre: "Philosophy/Life Improvement", pages: 336, priority: "2" },
  { title: "Hell's Angels: A Strange and Terrible Saga", genre: "Culture/Society", priority: "" },
  { title: "The Twelve Caesars", genre: "History/War", pages: 420, priority: "" },
  { title: "The Virgin Way", genre: "Business/Economics", pages: 400, priority: "" },
  { title: "Like a Virgin", genre: "Business/Economics", pages: 352, priority: "" },
  { title: "Screw It, Let's Do It", genre: "Philosophy/Life Improvement", pages: 111, priority: "" },
  { title: "The Man Who Would Be King", genre: "Fiction", pages: 114, notes: "Rudyard Kipling", priority: "" },
  { title: "The Clan of the Cave Bear", genre: "Fiction", pages: 512, notes: "Cavemen", priority: "" },
  { title: "To Kill a Mockingbird", genre: "Fiction", pages: 336, priority: "" },
  { title: "Stranger in a Strange Land", genre: "Fiction", pages: 608, priority: "" },
  { title: "The RSC Shakespeare: The Complete Works", genre: "Fiction", pages: 2552, priority: "" },
  { title: "The Complete Sherlock Holmes", genre: "Fiction", pages: 1136, priority: "" },
];

// Process and export books
export const books: Book[] = rawBooks
  .filter(book => book.priority !== 'X') // Filter out crossed out books
  .map((book, index) => {
    const { title, author } = parseTitle(book.title);
    return {
      id: `book-${index}`,
      title,
      author,
      genre: normalizeGenre(book.genre),
      pages: book.pages,
      notes: book.notes,
      priority: book.priority,
    };
  });

// Group books by genre
export function getBooksByGenre(): Record<string, Book[]> {
  const grouped: Record<string, Book[]> = {};

  for (const book of books) {
    if (!grouped[book.genre]) {
      grouped[book.genre] = [];
    }
    grouped[book.genre].push(book);
  }

  // Sort genres alphabetically, but put "Uncategorized" last
  const sortedGrouped: Record<string, Book[]> = {};
  const sortedKeys = Object.keys(grouped).sort((a, b) => {
    if (a === 'Uncategorized') return 1;
    if (b === 'Uncategorized') return -1;
    return a.localeCompare(b);
  });

  for (const key of sortedKeys) {
    sortedGrouped[key] = grouped[key];
  }

  return sortedGrouped;
}

// Get all unique genres
export function getGenres(): string[] {
  const genres = new Set(books.map(book => book.genre));
  return Array.from(genres).sort((a, b) => {
    if (a === 'Uncategorized') return 1;
    if (b === 'Uncategorized') return -1;
    return a.localeCompare(b);
  });
}
